
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_rest_demo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  project:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG: False
      DATABASE_URL: postgres://postgres:postgres@db:5432/django_rest_demo_db
    depends_on:
      - db

volumes:
  postgres_data:
